window.accesoriosData = [
  {
    codigo: "1",
    fileName: "estuchelentedecontacto_1_70bs.jpeg",
    isValid: true,
    precioBs: "70",
    categoria: "estuche lente de contacto",
  },
  {
    codigo: "2",
    fileName: "estuchelentedecontacto_2_40bs.jpeg",
    isValid: true,
    precioBs: "40",
    categoria: "estuche lente de contacto",
  },

  {
    codigo: "4",
    fileName: "estuchelentedecontacto_4_30bs.jpeg",
    isValid: true,
    precioBs: "30",
    categoria: "estuche lente de contacto",
  },
  {
    codigo: "5",
    fileName: "estuchelentedecontacto_5_35bs.jpeg",
    isValid: true,
    precioBs: "35",
    categoria: "estuche lente de contacto",
  },
  {
    codigo: "6",
    fileName: "estuchelentedecontacto_6_40bs.jpeg",
    isValid: true,
    precioBs: "40",
    categoria: "estuche lente de contacto",
  },
  {
    codigo: "7",
    fileName: "estuchelentedecontacto_7_60bs.jpeg",
    isValid: true,
    precioBs: "60",
    categoria: "estuche lente de contacto",
  },
  {
    codigo: "8",
    fileName: "estuchelentedecontacto_8_70bs.jpeg",
    isValid: true,
    precioBs: "70",
    categoria: "estuche lente de contacto",
  },
  {
    codigo: "200",
    fileName: "montura_200_200bs.jpeg",
    isValid: true,
    precioBs: "200",
    categoria: "montura",
  },
  {
    codigo: "2258t",
    fileName: "montura_2258t_1200bs.jpeg",
    isValid: true,
    precioBs: "1200",
    categoria: "montura",
  },
  {
    codigo: "2263a",
    fileName: "montura_2263a_1000bs.jpeg",
    isValid: true,
    precioBs: "1000",
    categoria: "montura",
  },
  {
    codigo: "230",
    fileName: "montura_230_230bs.jpeg",
    isValid: true,
    precioBs: "230",
    categoria: "montura",
  },
  {
    codigo: "2326t",
    fileName: "montura_2326t_1100bs.jpeg",
    isValid: true,
    precioBs: "1100",
    categoria: "montura",
  },
  {
    codigo: "2331t",
    fileName: "montura_2331t_1100bs.jpeg",
    isValid: true,
    precioBs: "1100",
    categoria: "montura",
  },
  {
    codigo: "85002",
    fileName: "montura_85002_1300bs.jpeg",
    isValid: true,
    precioBs: "1300",
    categoria: "montura",
  },
  {
    codigo: "85015",
    fileName: "montura_85015_1300.jpeg",
    isValid: true,
    precioBs: "1300",
    categoria: "montura",
  },
  {
    codigo: "91714",
    fileName: "montura_91714_1200bs.jpeg",
    isValid: true,
    precioBs: "1200",
    categoria: "montura",
  },
  {
    codigo: "95802",
    fileName: "montura_95802_1200bs.jpeg",
    isValid: true,
    precioBs: "1200",
    categoria: "montura",
  },
  {
    codigo: "95933",
    fileName: "montura_95933_450bs.jpeg",
    isValid: true,
    precioBs: "450",
    categoria: "montura",
  },
  {
    codigo: "95972",
    fileName: "montura_95972_1200bs.jpeg",
    isValid: true,
    precioBs: "1200",
    categoria: "montura",
  },
  {
    codigo: "97790",
    fileName: "montura_97790_1200bs.jpeg",
    isValid: true,
    precioBs: "1200",
    categoria: "montura",
  },
  {
    codigo: "1",
    fileName: "recuadrooftamologico_1_45bs.jpeg",
    isValid: true,
    precioBs: "45",
    categoria: "Cuadro Oftalmologico",
  },

  {
    codigo: "3",
    fileName: "recuadrooftamologico_3_130bs.jpeg",
    isValid: true,
    precioBs: "130",
    categoria: "Cuadro Oftalmologico",
  },
  {
    codigo: "4",
    fileName: "recuadrooftamologico_4_140bs.jpeg",
    isValid: true,
    precioBs: "140",
    categoria: "Cuadro Oftalmologico",
  },
  {
    codigo: "1",
    fileName: "repuestosvarillas_1_50bs.jpeg",
    isValid: true,
    precioBs: "50",
    categoria: "repuestos de varillas",
  },
];
