window.accesoriosData = [
  {
    codigo: "1",
    fileName: "estuchelentedecontacto_1_70bs.jpeg",
    isValid: true,
    precioBs: "70",
    categoria: "estuche lente de contacto",
  },
  {
    codigo: "2",
    fileName: "estuchelentedecontacto_2_40bs.jpeg",
    isValid: true,
    precioBs: "40",
    categoria: "estuche lente de contacto",
  },
  {
    codigo: "3",
    fileName: "estuchelentedecontacto_3_20bs.jpeg",
    isValid: true,
    precioBs: "20",
    categoria: "estuche lente de contacto",
  },
  {
    codigo: "4",
    fileName: "estuchelentedecontacto_4_30bs.jpeg",
    isValid: true,
    precioBs: "30",
    categoria: "estuche lente de contacto",
  },
  {
    codigo: "5",
    fileName: "estuchelentedecontacto_5_35bs.jpeg",
    isValid: true,
    precioBs: "35",
    categoria: "estuche lente de contacto",
  },
  {
    codigo: "6",
    fileName: "estuchelentedecontacto_6_40bs.jpeg",
    isValid: true,
    precioBs: "40",
    categoria: "estuche lente de contacto",
  },
  {
    codigo: "7",
    fileName: "estuchelentedecontacto_7_60bs.jpeg",
    isValid: true,
    precioBs: "60",
    categoria: "estuche lente de contacto",
  },
  {
    codigo: "8",
    fileName: "estuchelentedecontacto_8_70bs.jpeg",
    isValid: true,
    precioBs: "70",
    categoria: "estuche lente de contacto",
  },
  {
    codigo: "Dest80",
    fileName: "herramientas_Dest80_88bs.jpeg",
    isValid: true,
    precioBs: "88",
    categoria: "herramientas",
  },
  {
    codigo: "200",
    fileName: "montura_200_220bs.jpeg",
    isValid: true,
    precioBs: "220",
    categoria: "montura",
  },
  {
    codigo: "2258t",
    fileName: "montura_2258t_1320bs.jpeg",
    isValid: true,
    precioBs: "1320",
    categoria: "montura",
  },
  {
    codigo: "2263a",
    fileName: "montura_2263a_1100bs.jpeg",
    isValid: true,
    precioBs: "1100",
    categoria: "montura",
  },
  {
    codigo: "230",
    fileName: "montura_230_254bs.jpeg",
    isValid: true,
    precioBs: "254",
    categoria: "montura",
  },
  {
    codigo: "2326t",
    fileName: "montura_2326t_1210bs.jpeg",
    isValid: true,
    precioBs: "1210",
    categoria: "montura",
  },
  {
    codigo: "2331t",
    fileName: "montura_2331t_1210bs.jpeg",
    isValid: true,
    precioBs: "1210",
    categoria: "montura",
  },
  {
    codigo: "240",
    fileName: "montura_240_240bs.jpeg",
    isValid: true,
    precioBs: "240",
    categoria: "montura",
  },
  {
    codigo: "2C230",
    fileName: "montura_2C230_254bs.jpeg",
    isValid: true,
    precioBs: "254",
    categoria: "montura",
  },
  {
    codigo: "3C230",
    fileName: "montura_3C230_254bs.jpeg",
    isValid: true,
    precioBs: "254",
    categoria: "montura",
  },
  {
    codigo: "4C230",
    fileName: "montura_4C230_254bs.jpeg",
    isValid: true,
    precioBs: "254",
    categoria: "montura",
  },
  {
    codigo: "85002",
    fileName: "montura_85002_1430bs.jpeg",
    isValid: true,
    precioBs: "1430",
    categoria: "montura",
  },
  {
    codigo: "85015",
    fileName: "montura_85015_1430.jpeg",
    isValid: true,
    precioBs: "1430",
    categoria: "montura",
  },
  {
    codigo: "91714",
    fileName: "montura_91714_1320bs.jpeg",
    isValid: true,
    precioBs: "1320",
    categoria: "montura",
  },
  {
    codigo: "95802",
    fileName: "montura_95802_1320bs.jpeg",
    isValid: true,
    precioBs: "1320",
    categoria: "montura",
  },
  {
    codigo: "95933",
    fileName: "montura_95933_495bs.jpeg",
    isValid: true,
    precioBs: "495",
    categoria: "montura",
  },
  {
    codigo: "95972",
    fileName: "montura_95972_1320bs.jpeg",
    isValid: true,
    precioBs: "1320",
    categoria: "montura",
  },
  {
    codigo: "97790",
    fileName: "montura_97790_1320bs.jpeg",
    isValid: true,
    precioBs: "1320",
    categoria: "montura",
  },
  {
    codigo: "Al390",
    fileName: "montura_Al390_429bs.jpeg",
    isValid: true,
    precioBs: "429",
    categoria: "montura",
  },
  {
    codigo: "1",
    fileName: "recuadrooftamologico_1_45bs.jpeg",
    isValid: true,
    precioBs: "45",
    categoria: "Cuadro oftalmologico",
  },
  {
    codigo: "2",
    fileName: "recuadrooftamologico_2_85bs.jpeg",
    isValid: true,
    precioBs: "85",
    categoria: "Cuadro oftalmologico",
  },
  {
    codigo: "3",
    fileName: "recuadrooftamologico_3_130bs.jpeg",
    isValid: true,
    precioBs: "130",
    categoria: "Cuadro oftalmologico",
  },
  {
    codigo: "4",
    fileName: "recuadrooftamologico_4_140bs.jpeg",
    isValid: true,
    precioBs: "140",
    categoria: "Cuadro oftalmologico",
  },
  {
    codigo: "1",
    fileName: "repuestosvarillas_1_50bs.jpeg",
    isValid: true,
    precioBs: "50",
    categoria: "repuestos de varillas",
  },
];
